name: pypy-notebook

channels:
  - conda-forge
  - nodefaults

dependencies:
  - jupyterlab==3.3.3
  - numpy
  - matplotlib
  - pandas
  - ipywidgets
  - jupyterlab-vpython
  - pypy
  - pip
  - pip:
    - vpython
